### PR TITLE
Set Title Function Fixed

### PR DESCRIPTION
**Pull request by GeigerCounter**
Now with Windows support!

### CODE REVIEW

**Comment by zyedidia** [comment]
Sorry I'll get around to this soon.

**Comment by zyedidia** [comment]
Just a couple notes:

Instead of using `strings.Compare(os.Getenv("TERM") , "screen") == 0` you could just write `os.Getenv("TERM") == "screen"`.

Unless you are certain these escape sequences work for all terminal types, I think you should check to make sure the terminal contains `xterm` before applying them (but not for the screen one obviously). So before doing the `\033...\007` just check if `strings.Contains(os.Getenv("TERM"), "xterm")` (also make sure to check in the `Fini` function as well).

This means that the terminal title setting will only work in screen and xterm but I think that's acceptable.

Otherwise it looks good. I'm glad the windows support works!

**Comment by GeigerCounter** [comment]
@zyedidia Sorry about the radio silence. For one, I totally missed the notification for these comments. For another, I've been in and still am in the process of moving. We're actually in the house now, so that's nice, but over the next week I should be fairly busy with various errands. Also, I suppose I can do that, though I'd have to add another line in after the logic to check if the terminal is a screen. And uh, anyways. The only major, widely used terminal I didn't check is Konsole. I already checked and the escapes work on:

- gnome-terminal
- mate-terminal
- urxvt
- xfce4-terminal

And cause no error and no effect on: 
- linux terminal for at least >= kernel version 3.xx
- actual xterm 

I don't know if this is wide enough support and I don't know what the escape codes would do on true POSIX or VT100 emulators to be honest, so I'll go ahead and put in the logic. ( On the other side of the coin, I don't know anyone who actually *uses* true POSIX compatible terminals or VT100 emulators. ) For bonus points, I'll test the control codes on Konsole.

**Comment by GeigerCounter** [comment]
@zyedidia I put in the logic with the merge since I had to resolve the conflicts anyway. Probably should've done it in two commits, but oh well. Should be ready to merge whenever you're ready to merge it.

**Pull request merged**
